# Cloudflare Pages configuration
name = "aaronsmolyar-com"
pages_build_output_dir = "dist"

[build]
command = "npm install && npm run build"
publish = "dist"

[site]
bucket = "dist"

[build.environment]
NODE_VERSION = "18" 